apiVersion: v1
kind: Service
metadata:
  name: admission-kube-webhook-svc
  namespace: ikube
  labels:
    app: admission-kube-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  type: ClusterIP
  selector:
    app: admission-kube-webhook
