apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-webhook-deployment
  namespace: ikube
  labels:
    app: admission-kube-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admission-kube-webhook
  template:
    metadata:
      labels:
        app: admission-kube-webhook
    spec:
      containers:
        - name: admission-kube-webhook
          image: reg.harbor.com/ikube/kube-webhook:v2
          imagePullPolicy: IfNotPresent
          args:
            - -tlsCertPath=/etc/webhook/certs/cert.pem
            - -tlsKeyPath=/etc/webhook/certs/key.pem
            - -portConfigFile=/etc/webhook/conf/ports.conf
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/conf
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-kube-webhook-certs
        - name: webhook-config
          configMap:
            name: kube-webhook-prod-configmap

